/* 
 * Material didático destinado ao curso
 * de Programação Orientada a Objetos do 
 * Bacharelado em Ciência da Computação 
 * do IFNMG - Câmpus Montes Claros
 */
package com.mycompany.jogos;

import com.mycompany.jogos.repositorio.ContaPrincipalDao;
import com.mycompany.jogos.entidades.Conta;
import com.mycompany.jogos.entidades.ContaPrincipal;
import com.mycompany.jogos.entidades.Usuario;
import com.mycompany.jogos.repositorio.ContaDao;
import com.mycompany.jogos.repositorio.UsuarioDao;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Luis Guisso <luis dot guisso at ifnmg dot edu dot br>
 * @version 0.0.1, 16/08/2021
 */
public class IjfContaPrincipal extends javax.swing.JInternalFrame {

    private static IjfContaPrincipal self;
    private Conta conta;
    private ContaPrincipal contaPrincipal;

    /**
     * Creates new form InternaC
     */
    private IjfContaPrincipal() {
        conta = new Conta();
        contaPrincipal = new ContaPrincipal();
        initComponents();
        atualizarCmb();
    }

    public static IjfContaPrincipal getInstance() {
        // Caso a janela ainda não tenha sido instanciada
        if (self == null) {
            self = new IjfContaPrincipal();
        }

        return self;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpPrincipal = new javax.swing.JPanel();
        jbtInserir = new javax.swing.JButton();
        jbtAtualizar = new javax.swing.JButton();
        jbtRecuperar = new javax.swing.JButton();
        jbtExcluir = new javax.swing.JButton();
        jbtListar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jtfLogin = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtfApelido = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtfPerguntaDeSeguranca = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtfRspostaDeSeguranca = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cmbUsuario = new javax.swing.JComboBox<>();
        jpfSenha = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        cmbConta = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setTitle("Cadastro de contas principais");

        jbtInserir.setText("Inserir");
        jbtInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtInserirActionPerformed(evt);
            }
        });

        jbtAtualizar.setText("Atualizar");
        jbtAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAtualizarActionPerformed(evt);
            }
        });

        jbtRecuperar.setText("Limpar");
        jbtRecuperar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtRecuperarActionPerformed(evt);
            }
        });

        jbtExcluir.setText("Excluir");
        jbtExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtExcluirActionPerformed(evt);
            }
        });

        jbtListar.setText("Listar");
        jbtListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtListarActionPerformed(evt);
            }
        });

        jLabel1.setText("LOGIN");

        jLabel2.setText("SENHA");

        jLabel3.setText("APELIDO");

        jLabel4.setText("PERGUNTA DE SEGURANÇA");

        jLabel5.setText("RESPOSTA DE SEGURANÇA");

        jLabel6.setText("USUÁRIO");

        jpfSenha.setText("jPasswordField1");

        jLabel7.setText("SELECIONA CONTA PRINCIPAL");

        cmbConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbContaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpPrincipalLayout = new javax.swing.GroupLayout(jpPrincipal);
        jpPrincipal.setLayout(jpPrincipalLayout);
        jpPrincipalLayout.setHorizontalGroup(
            jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jpPrincipalLayout.createSequentialGroup()
                .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpPrincipalLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jbtInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtRecuperar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtExcluir)
                        .addGap(18, 18, 18)
                        .addComponent(jbtListar, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPrincipalLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpPrincipalLayout.createSequentialGroup()
                                .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(12, 12, 12))
                            .addGroup(jpPrincipalLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(102, 102, 102)))
                        .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbUsuario, 0, 275, Short.MAX_VALUE)
                            .addComponent(jtfRspostaDeSeguranca, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                            .addComponent(jtfPerguntaDeSeguranca, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                            .addComponent(jtfApelido, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                            .addComponent(jtfLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                            .addComponent(jpfSenha)
                            .addComponent(cmbConta, 0, 275, Short.MAX_VALUE))))
                .addContainerGap())
        );

        jpPrincipalLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jbtExcluir, jbtInserir, jbtListar});

        jpPrincipalLayout.setVerticalGroup(
            jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPrincipalLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(16, 16, 16)
                .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jpfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfApelido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(16, 16, 16)
                .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfPerguntaDeSeguranca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(16, 16, 16)
                .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfRspostaDeSeguranca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(16, 16, 16)
                .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmbUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cmbConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbtRecuperar)
                        .addComponent(jbtExcluir)
                        .addComponent(jbtListar))
                    .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbtInserir)
                        .addComponent(jbtAtualizar)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtInserirActionPerformed
        // TODO add your handling code here:
        getDadosTela();
        try {
            // TODO add your handling code here:
            if (new ContaPrincipalDao().findByPk(contaPrincipal) != null) {
                JOptionPane.showMessageDialog(this, "já cadastraado");
                return;
            }
            new ContaDao().saveOrUpdate(conta, true);
            new ContaPrincipalDao().saveOrUpdate(contaPrincipal, true);
            contaPrincipal.setConta(conta);
            limparDadosTela();
            getDadosTela();
            atualizarCmb();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_jbtInserirActionPerformed

    private void jbtAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAtualizarActionPerformed
        // TODO add your handling code here:
        getDadosTela();
        try {
            // TODO add your handling code here:
            if (new ContaPrincipalDao().findByPk(contaPrincipal) == null) {
                new ContaDao().deleteByPk(conta);
                JOptionPane.showMessageDialog(this, "não cadastraado");
                return;
            }
            new ContaDao().saveOrUpdate(conta, false);
//            new ContaPrincipalDao().saveOrUpdate(contaPrincipal, false);
            limparDadosTela();
            getDadosTela();
            atualizarCmb();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }

    }//GEN-LAST:event_jbtAtualizarActionPerformed

    private void jbtRecuperarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtRecuperarActionPerformed
        // TODO add your handling code here:
        limparDadosTela();

    }//GEN-LAST:event_jbtRecuperarActionPerformed

    private void jbtExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtExcluirActionPerformed
        // TODO add your handling code here:
        getDadosTela();
        try {
            // TODO add your handling code here:
            if (new ContaPrincipalDao().findByPk(contaPrincipal) == null) {
                new ContaDao().deleteByPk(conta);
                JOptionPane.showMessageDialog(this, "não cadastrado");
                return;
            }

            new ContaDao().deleteByPk(conta);

            if (new ContaDao().findByPk(conta) != null) {
                JOptionPane.showMessageDialog(this, "não Excluido");
                return;
            }

            new ContaPrincipalDao().deleteByPk(contaPrincipal);
            limparDadosTela();
            getDadosTela();
            atualizarCmb();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_jbtExcluirActionPerformed

    private void jbtListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtListarActionPerformed
        // TODO add your handling code here:
        new Util().relatorios("/ContaPrincipal.jasper", "Listagem de ContaPrincipals");
    }//GEN-LAST:event_jbtListarActionPerformed

    private void cmbContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbContaActionPerformed
        // TODO add your handling code here:       
        conta = (Conta) cmbConta.getModel().getSelectedItem();
        setDadosTela();
    }//GEN-LAST:event_cmbContaActionPerformed

//    private String login;
//    private String senha;
//    private String apelido;
//    private String perguntaDeSeguranca;
//    private String respostaDeSeguranca;
    private void getDadosTela() {
        if (contaPrincipal == null) {
            contaPrincipal = new ContaPrincipal();
        }
        conta.setLogin(jtfLogin.getText());
        conta.setSenha(new String(jpfSenha.getPassword()));
        conta.setApelido(jtfApelido.getText());
        conta.setPerguntaDeSeguranca(jtfPerguntaDeSeguranca.getText());
        conta.setRespostaDeSeguranca(jtfRspostaDeSeguranca.getText());
        contaPrincipal.setLoginConta(jtfLogin.getText());
        contaPrincipal.setConta(conta);
        conta.setUsuario((Usuario) cmbUsuario.getSelectedItem());
    }

    private void setDadosTela() {
        if (contaPrincipal == null) {
            contaPrincipal = new ContaPrincipal();
        }
        jtfLogin.setText(conta.getLogin());
        jpfSenha.setText(conta.getSenha());
        jtfApelido.setText(conta.getApelido());
        jtfPerguntaDeSeguranca.setText(conta.getPerguntaDeSeguranca());
        jtfRspostaDeSeguranca.setText(conta.getRespostaDeSeguranca());
        cmbUsuario.getModel().setSelectedItem(conta.getUsuario());

    }

    private void limparDadosTela() {
        jtfLogin.setText("");
        jpfSenha.setText("");
        jtfApelido.setText("");
        jtfPerguntaDeSeguranca.setText("");
        jtfRspostaDeSeguranca.setText("");
        cmbUsuario.getModel().setSelectedItem(null);
//        cmbConta.getModel().setSelectedItem(null);
    }

    private void atualizarCmb() {
        DefaultComboBoxModel<Usuario> comboBoxModelUsuario = new DefaultComboBoxModel<>();
        try {
            comboBoxModelUsuario.addAll(new UsuarioDao().findAll());
        } catch (Exception ex) {
            Logger.getLogger(IjfContaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        cmbUsuario.setModel(comboBoxModelUsuario);

        DefaultComboBoxModel<Conta> comboBoxModelConta = new DefaultComboBoxModel<>();
        try {
            comboBoxModelConta.addAll(new ContaDao().localizarTodasContasPincipais());
        } catch (Exception ex) {
            Logger.getLogger(IjfContaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        cmbConta.setModel(comboBoxModelConta);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Conta> cmbConta;
    private javax.swing.JComboBox<Usuario> cmbUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton jbtAtualizar;
    private javax.swing.JButton jbtExcluir;
    private javax.swing.JButton jbtInserir;
    private javax.swing.JButton jbtListar;
    private javax.swing.JButton jbtRecuperar;
    private javax.swing.JPanel jpPrincipal;
    private javax.swing.JPasswordField jpfSenha;
    private javax.swing.JTextField jtfApelido;
    private javax.swing.JTextField jtfLogin;
    private javax.swing.JTextField jtfPerguntaDeSeguranca;
    private javax.swing.JTextField jtfRspostaDeSeguranca;
    // End of variables declaration//GEN-END:variables
}
